### PR TITLE
Create settings.json

### PR DESCRIPTION
**Pull request by ranodeepbanerjee**
Added Vscode Settings

### CODE REVIEW

**Comment by gewenyu99** [comment]
@stnguyen90 I don't think we meant to check in vscode settings in our repos, right? We should in fact not have this folder at all?

**Comment by stnguyen90** [comment]
@gewenyu99 in general, it's a nice thing to have as it enforces consistency. I'm just not sure we want to accept this for hacktoberfest.

**Comment by gewenyu99** [comment]
Yeah, I don't feel like this would be an acceptable hacktoberfest contribution. @stnguyen90 Maybe we can accept this but label invalid?

**Comment by stnguyen90** [comment]
Let's close this for now. We can revisit this internally if we really want to add this to our repos.

**Pull request closed without merging**
